# SPDX-FileCopyrightText: 2021 Pen-Yuan Hsing
#
# SPDX-License-Identifier: CC0-1.0

# Configuration file for data miner backend
# Uncommented and customise items to use them
# All paths are relative to the root of this repository `wp2.2_dev`

# Path to CSV file containing list of repositories to mine
repo_list: input/OSH-repos.csv

# Data directory where data mined by `osmine` is saved
data_dir: data

# Create 
#create_data_dir: True

# (optional) Path to file containing GitHub authentication token as a alphanumeric string
#GitHub_token: token